os: linux
dist: trusty
sudo: required
group: edge
language: c
branches:
  except:
    - /^.*-automated-build$/
    - /^[0-9]+\.[0-9]+\.[0-9]+/
before_install:
  - wget http://ww1.microchip.com/downloads/en/DeviceDoc/avr8-gnu-toolchain-3.5.4.1709-linux.any.x86_64.tar.gz || wget http://qmk.fm/avr8-gnu-toolchain-3.5.4.1709-linux.any.x86_64.tar.gz
install:
  - tar -zxf avr8-gnu-toolchain-3.5.4.1709-linux.any.x86_64.tar.gz
  - export PATH="$PATH:$TRAVIS_BUILD_DIR/avr8-gnu-toolchain-linux_x86_64/bin"
  - npm install -g moxygen
before_script:
  - avr-gcc --version
script:
- make dz60:weeheavy AUTOGEN=false
addons:
  apt:
    packages:
    - dfu-programmer
    - pandoc
    - gcc-arm-none-eabi
    - binutils-arm-none-eabi
    - libnewlib-arm-none-eabi
    - diffutils
    - dos2unix
    - doxygen
before_deploy:
  - git config --local user.name "weeheavy QMK bot"
  - git config --local user.email "nothing@example.org"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: "oTae9e2OsvGjkgiz4hZxIK1gLXVwYvr1fkRRlWnWG3Qo5aWCUdU0oaSzs8dFuVaZpzr5cP1Qtl0nPN/e2S+/0qYZWFaXvZNaITnEGF/1ey7J9djnFjZB4aoGECKVKy3NIxlklMOsHIUacUI1GGsaQ0Mw0qqVAyyGQ/ODZDUae5fWBIw7tiZ3hZMmc4huSC++x0o5CfGOwXqWl6oEUKj9rVTmd2/DtD8EOQXkGSxRSYtZeAj7HuRyy6UVkORaIQ5PJQkxC1NrDi5AsjfxKO+00bBnZMRqcDjfTTjAozaLL4gwnI/KwwDQATcA2faA83RAzxsWGwvpV4YD3i6wZxn8XAp2hI3Hc1k2esYicw312s0m7EptvfPEvLZ48XgSV9J3MBlWFyF3djtYHr9bQT9gXdKHWmju+OCAp1QKj8nPACS4tpnoGZJmbT2uIRV2oBNB2dki9EP1b45iPKxWQT/Sw1COgYB5hOkmQwvXZxnAG6Zdv1XJLp7wL34MKUntsOfNMIPxXoSlTeTIThs7J8kyW4G1a6adxhzvWCSldbe8qbyPl5ILvTNwXcBg3yNTUZG4Iha3KWDB5D7vUyj6AD8gJkflXX65eMo+WVxaid6Y/BtNFOZLEJ1CbS3YJ8UJeVCtyY/+x/TjuwF+gwZhg3sZTZffuJ2NOBEVk+mdqBIsUYQ="
  file: dz60_weeheavy.hex
  skip_cleanup: true
